name: build_windows

on:
  push:
    branches:
      - ci-test

jobs:
  build:
    if: contains(github.event.head_commit.message, '[push windows]')
    runs-on: windows-latest
    environment: windows
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'
      - name: Install Windows SDK
        run: choco install windows-sdk-10
      - name: Install Certificate to Store and Clean Up
        run: |
          $base64EncodedCert = "${{ secrets.CERTIFICATE_ENCODED }}"
          $certBytes = [System.Convert]::FromBase64String($base64EncodedCert)
          [System.IO.File]::WriteAllBytes("simbrain.p12", $certBytes)
          $pfxPassword = ConvertTo-SecureString -String "${{ secrets.CERTIFICATE_PASSWORD }}" -AsPlainText -Force
          Import-PfxCertificate -FilePath "simbrain.p12" -CertStoreLocation Cert:\LocalMachine\My -Password $pfxPassword
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build with Gradle
        run: ./gradlew signWindowsApp
        env:
          CERTIFICATE_SHA1: ${{ vars.CERTIFICATE_SHA1 }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Simbrain-Windows
          path: build/dist/Simbrain*.exe
  push:
    needs: build
    runs-on: ubuntu-latest
    environment: cloudflare
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: Simbrain-Windows
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS CLI for Cloudflare R2
        env:
          R2_ACCESS_KEY: ${{ secrets.R2_ACCESS_KEY }}
          R2_SECRET_KEY: ${{ secrets.R2_SECRET_KEY }}
        run: |
          aws configure set aws_access_key_id $R2_ACCESS_KEY
          aws configure set aws_secret_access_key $R2_SECRET_KEY
          aws configure set default.region auto

      - name: Upload to Cloudflare R2
        env:
          CLOUDFLARE_R2_BUCKET: ${{ secrets.CLOUDFLARE_R2_BUCKET }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          aws s3 cp Simbrain*.exe s3://$CLOUDFLARE_R2_BUCKET/ --endpoint-url=https://$CLOUDFLARE_ACCOUNT_ID.r2.cloudflarestorage.com
